- name: Deploy to EC2
  hosts: localhost
  connection: local

  tasks:
    - name: Launch EC2 instance
      ec2:
        instance_type: t2.micro
        image: ami-0747bdcabd34c712a
        region: us-east-1
        key_name: devops
        vpc_subnet_id: subnet-c26f578f
        assign_public_ip: yes
        wait: yes
        count: 1
        aws_access_key: "{{lookup('env', 'AWS_ACCESS_KEY_ID')}}"
        aws_secret_key: "{{lookup('env', 'AWS_SECRET_ACCESS_KEY')}}"
        security_token: "{{lookup('env', 'AWS_SESSION_TOKEN')}}"
      register: ec2
